### ISSUE TITLE
Improvements of the genetics etl for platform integration

### ISSUE THREAD

**Issue by project-defiant** [opentargets/orchestration#57]
# Context

Genetics etl dag described by the image below
![Image](https://github.com/user-attachments/assets/d7ef40a2-6f19-438a-a7e2-3befb2b81d66)

should be possible to execute in two modes:
- run with the unified pipeline
- run in standalone mode

Here is the list of possible improvements that I can see, can fit the `genetics_etl` dag to fit the above conditions:
 
1. Extract `variant_to_vcf` and `list_nonannotated_variants` as a single dataproc step

Currently `varaiant_to_vcf` step uses sources from the etl, namely: 
- gs://open-targets-pre-data-releases/24.09/input/evidence-files/uniprot.json.gz
- gs://open-targets-pre-data-releases/24.09/input/evidence-files/eva.json.gz
- gs://open-targets-pre-data-releases/24.09/input/pharmacogenomics-inputs/pharmacogenomics.json.gz

* evidence-files comes directly from the PIS (no other dependencies)
* pharmacogenomics-inputs are generated by platform ETL 

As first step `variant_to_vcf` is run as a google batch job and second step `list_nonannotated_variants` is run as a standalone task (pythonOperator) can be submerged and run as a single dataproc step, we could decrese the complexity of the pipeline by removing the batch job and it's configuration, so it's more generic and easier to transfer to unified pipeline.

2. Extract the configuration of the steps and submerge as a unified pipeline config empowered by hydra. This will roll back the steps to the way how they were handled before in gentropy - see https://github.com/opentargets/gentropy/tree/v1.7.0/config, but decomplexified by only hosting the config for the genetics_etl steps.

This would mean that we could store one config per way how we run the pipeline:
- default config for standalone execution mode
- one config for unified pipeline that overrides the default config paths.

**Comment by project-defiant** [comment]
@javfg These are the things we discussed summarized

**Comment by project-defiant** [comment]
The full list of back and forth dependencies:

ETL -> Genetics dependencies
* etl_target -> genetics_gene_index
* pis_biosamples -> genetics_biosample_index
* etl_diseases -> genetics_study_index
* pis_evidence -> genetics_variant_conversion
* pis_pharmacogenomics -> genetics_variant_conversion
* etl_interactions -> genetics_l2g_train`

Genetics -> ETL dependencies
* gentropy_l2g_evidence  -> etl_evidence (store l2g_evidence in pis_evidence output)
* gentropy_variant_index -> etl_seach

> [!NOTE]
> Steps from `genetics_etl` dag are prefixed with `genetics_`

**Comment by project-defiant** [comment]
Update on `variant_annotation`

The PR https://github.com/opentargets/orchestration/pull/67 Included changes that dropped the complexity of the genetics_etl variant annotation tasks. See the dag below

![Image](https://github.com/user-attachments/assets/4b884785-3400-496b-b550-ec03a052e302)

Details of the changes are listed in the PR description.

**Comment by project-defiant** [comment]
This is a full topology of the direct dependencies for platform run as opposed to the simplified dag with indirect dependencies see comment above

![Image](https://github.com/user-attachments/assets/313591d3-a373-4805-bb3f-92800e543b81)

 * indirect depencency in this context means that links between the current step and some previous step that was already required by  current step predecessor are skipped

**Comment by javfg** [comment]
> This is a full topology of the direct dependencies for platform run as opposed to the simplified dag with indirect dependencies see comment above
> 
> ![Image](https://github.com/user-attachments/assets/313591d3-a373-4805-bb3f-92800e543b81)
> 
>     * indirect depencency in this context means that links between the current step and some previous step that was already required by  current step predecessor are skipped

As we discussed, this graph is missing a `genetics_variant_annotation` node which has an upstream dependency on `genetics_variant_conversion` and is itself an upstream dependency of `genetics_variant_index`. I'll leave it noted here so we don't get confused later on.

**Comment by javfg** [comment]
This is finished, pending some changes in the way we are handling permissions in the methods used for managing Google Batch in the Orchestrator.
